language: java
jdk:
  - openjdk8

services:
  - mysql

branches:
  only:
    - gh-pages
    - master

# Travis CI 서버의 home
cache:
  directories:
    - '$Home/.m2/repository'
    - '$Home/.gradle'

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS my_daily_feed;'
  - mysql -u root -e "CREATE USER 'jiwon'@'localhost' IDENTIFIED BY 'jiwon';"
  - mysql -u root -e "GRANT ALL ON my_daily_feed.* TO 'jiwon'@'localhost';"

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jwb8705@gmail.com
