handlebars:
  suffix: .html
  expose-session-attributes: true
  cache: false

spring:
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
    datasource:
        username: jiwon
        password: jiwon
        url: jdbc:mysql://localhost/my_daily_feed
        driverClassName: com.mysql.jdbc.Driver

#spring:
#  datasource:
#    username: jiwon
#    password: jiwon
#    url: jdbc:h2:~/my_daily_feed
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true
#  devtools:
#    livereload:
#      enabled: true

logging:
  pattern:
    level: trace





