handlebars:
  suffix: .html
  expose-session-attributes: true
  cache: false

spring:
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
    datasource:
        username: jiwon
        password: jiwon
        url: jdbc:mysql://localhost/my_daily_feed
        driverClassName: com
    devtools:
      livereload:
        enabled: true

logging:
  pattern:
    level: trace





